apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ratingsapi-hpa
  namespace: aks-engine-workshop-qa
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: ratingsapi-deploy
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60